### ISSUE TITLE
How do I set GUI_SESSION_PID?

### ISSUE THREAD

**Issue by root2185** [eylles/shed#1]
> ... the way this works is that shed is ran in either the user xinitrc or xsession file (debian and derivates use .xsession while most other distros use .xinitrc), shed needs to recieve the PID of the session through the env var GUI_SESSION_PID ...

I am not sure to how do that.

And do I need to use the `.xsession` file? Or can you just start it somehow?

**Comment by eylles** [comment]
ah, i forgot to explain that, if you use a debian-like distro then in .xsession, otherwise in .xinitrc (i have both files be the same with a symlink) add this:

```sh
export GUI_SESSION_PID=$$
```
i will add something to have shed use the pid of it's parent as a fallback if GUI_SESSION_PID isn't set.

**Comment by root2185** [comment]
Do you need to use .xsession (or .xinitrc)?
Or can you use some file to execute that? e.g. the openbox's autostart.

**Comment by eylles** [comment]
well, shed can be started anywhere within the session hierarchy, but it is necesary that the PID held by `GUI_SESSION_PID` be the one pid that is actually keeping the graphical session alive, say if you log in via a display manager, then the process that the display manager runs to start the session and that then will start the window manager and others.

in the following screenshot since i use the `.xsession` file to launch shed and the window manager (awesome), the process `.xsession` is the one keeping the x session alive, and thus necessary to use it's PID as `GUI_SESSION_PID` so that when `shedc logout` is ran, shedc will know what process to kill in order to end the session after killing the other processes.


![Screenshot at 2022-09-16 11-50-36](https://user-images.githubusercontent.com/33670677/190701735-b45e36b3-7820-47a9-97f2-ef3614e10e7b.png)


i hope i'm being clear.
